### PR TITLE
NLS/i18n: add Native Language Support, fixes #13

### LINKED ISSUE #13: Do we want NLS for this?
As title says - and I have `gettext` experience in `C` programs.

And I _could_  pilfer many of the translated strings from the QT version :thinking:

### PR DESCRIPTION
**Pull request by 01micko**
Includes rough translations for it and es,
Italian and Spanish respectively

### CODE REVIEW

**Comment by 01micko** [comment]
There is a bit to digest here so don't mind if it takes a while to merge. It's probably the biggest PR in terms of changes so far in this little project. I'll explain the rationale for my decisions below. 

1. I had to add add some tests and configuration in `meson.build` and created a `meson_options.txt` to allow disabling of `nls` feature, it is enabled by default if `msgfmt` is found, but can be overridden. This requires the creation of `config.h` and works exactly the same as the NLS implementation of `labwc` (which I wrote).
2. Since we now have a new header I had to include that in another header so I chose `state.h` which is common to the files that have strings which are exposed in the `Gtk` graphical interface.
3. `it` and `es` translations are included and are mostly borrowed from `labwc-tweaks` (Qt). Strings missing I used the translation feature in Vivaldi Browser (chromium clone) The translation is powered by [Lingavex](https://lingvanex.com)
4. Screenshots can be seen in #13 
5. The `labwc-tweaks-gtk.desktop` files also has the `it` and `es` rough translations.
6. To test (you need `gettext` tools)
   - get my fork and build with `meson setup build -Dprefix=/usr`
   - `meson compile -C build/`
   - `DESTDIR=$(pwd)some-extension meson install -C build`
   - in the directory created you have to install the `usr/share/locale/[it,es]` translations to the corresponding dirs on your system because meson hard codes that in the `po/meson.build` script. It didn't work with `/usr/local` for me.
   - just run the binary in `usr/bin` with `LANGUAGE=it ./labwc-tweaks-gtk` and you should get the translated GUI

Hopefully, if merged, we can get the Weblate folks to add more translations (and fix up my bad ones).

**Comment by 01micko** [comment]
Here's a screenshot on my laptop that's running very recent `labwc` - no nonsense in the Button Layout and Show Title fields.

it-latest

**Comment by johanmalm** [comment]
Thanks. Nice :smile:

**Comment by 01micko** [comment]
Thanks @johanmalm 

@stefonarch can you let weblate know about this please?

**Pull request merged**
