### PR TITLE
add titlebar button layout option and show/hide title

### PR DESCRIPTION
**Pull request by davidphilipbarr**
this adds an entry field for the button layout as well as a combo yes/no to show or hide the title.

### CODE REVIEW

**Comment by davidphilipbarr** [comment]
quick pic for reference 
20241004_11h54m25s_grim

**Comment by 01micko** [comment]
IMO, without a lot of parsing of the input for errors, using the entry widget could be more trouble than what it's worth. One typo could potentially mess up someone's setup.

**Comment by davidphilipbarr** [comment]
I don't think it would need that much validation to make it safe(ish) - i'm more in favour of the combo list myself but then we'd limit the options, but i don't think every option needs exposing in a gui? I originally used a dropdown but thought this way was more flexible, so i'm open to switching it back.

**Comment by johanmalm** [comment]
Shall I merge this for now?

When I get a few hours (probably after the labwc release), I'll implement something interactive for titlebar layout in the Qt version. Then we can take a view on how sophisticated we go with this.

**Comment by 01micko** [comment]
Fine by me, I'll help out where I can.

**Comment by 01micko** [comment]
Just a simple workflow for checking the string.
1. check for the delimiters `:` `,`   and appropriate number of each
2. if that passes convert `:` to `,` or allow both in our parser (probably the latter)
3. iterate through comparing the minimum and maximum number of words allowed
4. iterate through checking for dups
5. iterate through checking against a the list of allowed words
6. if those are all met we allow it through

handling failure
1. we need to inform the user of their mistake
2. since this is GUI needs to be by GUI
3. What?
    - system notification? (extra dependency)
    - internal GUI? (more code)
    - maybe a tooltip? (easy but maybe not as obvious)
    - change the background of the entry widget to a warn color (hot pink?) and tooltip (I like this, one easy and obvious)

If we intend to move forward with something else ignore this rant :laughing:

**Comment by davidphilipbarr** [comment]
I think @01micko is right this would be the ideal situation, but i'm going to try and implement font settings next, as i think this will make it feature useful and then reconsider the interface in general. there are a couple of others things like if the setting is missing create it and don't write to rc if nothing changes and so on i guess at a basic level. It's perfect for me right now to fling around ideas and test things. I've only a basic knowledge of c and i'm learning (copy pasting)  gtk as i go so...

**Pull request merged**
