### PR TITLE
add button layout and dropshadow options (badly)

### PR DESCRIPTION
**Pull request by davidphilipbarr**
very poorly hack in to extra bits in a vague hope of keeping this alive...

### CODE REVIEW

**Comment by davidphilipbarr** [comment]
Also allows for greater border radius I just saw (basically to match gnome)

**Comment by johanmalm** [comment]
Could you split them into separate commits and PRs?

Happy to merge radius increase and drop-shadow combo.

I have two reservations about the `titleLayout` setting:

1. We haven't agreed the syntax yet. Yes, we've merged something, but are talking about changing it and are likely to before the next release.
2. We ought to consider something more sophisticated. For example: https://docs.xfce.org/xfce/xfwm4/preferences

**Comment by davidphilipbarr** [comment]
yeah the title layout is total chaos anyway, it's even worse in my local branch, sorry - i mostly just use it to test svg buttons quickly.

i'll split options into individual prs  (i have even more) - if this project is not abandoned for the qt version i might try and spend some time trying to spruce it up a little, within my limited abilities. i'd not even considered the font options, or probably a lot of others that are quite important.

**Comment by johanmalm** [comment]
> if this project is not abandoned for the qt version i might try and spend some time trying to spruce it up a little, within my limited abilities. i'd not even considered the font options, or probably a lot of others that are quite important.

It's not abandoned, but I think it's fair to say that it doesn't get a lot of attention either. There are people who prefer it to the Qt version, so after some discussion we decided to leave it as a separate project.

I did try to port it GTK4 with a .ui file, but found it hard with glade not being GTK4 compatible and not many examples around to look at (that I could find anyway).

I will personally develop the Qt version, but am happy to review/merge/discuss/help/etc with this one.

**Comment by johanmalm** [comment]
Could you give me a nudge when/if you want me to review + merge.

Regarding titlebar-layout, https://github.com/labwc/labwc/pull/2128 is imminent, so may wish to hang out for that.

**Comment by 01micko** [comment]
I think the gtk version has it's place as a lighter, in terms of toolkit, alternative. I'm happy to help out with my similar limited abilities @davidphilipbarr .
One thing, we probably should keep up to speed with the qt version in terms of features.
@johanmalm I fully understand the frustration with gtk4!

**Comment by davidphilipbarr** [comment]
I've become a little distracted by the font selector. So far i think i've
added: increase border radius, shadow, placement, top maximise and double
click time as well as updated the button layout stuff and show/hide title -
these are really just options i've been playing with rather than things
that might be considered important generally.

So far it's all been copy and paste so adding fonts and entry fields is
taking a bit more time to wrap my head around. Layout probably should be
entry not combo, but it's very gnome to force limited choices on people :)

I don't really know anything about qt and i've never seen the qt tweaks
version, but it would make sense to aim for parity and probably ui
similarity - I've looked at porting to gtk4/libadwaita using blueprint,
which might be quite viable in the long run?

I'm getting ahead of myself  - i'll prioritise splitting them down and
getting them merged.

**Pull request closed without merging**
