### PR TITLE
stack*.c: capitalize all the headings.

### PR DESCRIPTION
**Pull request by 01micko**
Just for consistency with qt version.

### CODE REVIEW

**Comment by 01micko** [comment]
I threw the second one in this PR, you know I hate warnings @johanmalm :laughing:

**Comment by johanmalm** [comment]
Capitalisation looks good to me, but it would be better to fix the warning with this patch:

```
diff --git a/update.c b/update.c
index dedc3cc..56d3f62 100644
--- a/update.c
+++ b/update.c
@@ -58,7 +58,7 @@ update(GtkWidget *widget, gpointer data)
 	xml_set("/labwc_config/theme/name", COMBO_TEXT(state->widgets.openbox_theme_name));
 	xml_set("/labwc_config/libinput/device/naturalscroll", COMBO_TEXT(state->widgets.natural_scroll));
 	xml_set("/labwc_config/theme/dropShadows", COMBO_TEXT(state->widgets.drop_shadows));
-	xml_set("/labwc_config/theme/titlebar/layout", GTK_ENTRY_TEXT(state->widgets.button_layout));
+	xml_set("/labwc_config/theme/titlebar/layout", (char *)GTK_ENTRY_TEXT(state->widgets.button_layout));
 	xml_set("/labwc_config/theme/titlebar/showTitle", COMBO_TEXT(state->widgets.show_title));
 	xml_save();
```

**Comment by 01micko** [comment]
Yeah, me over doing it! I'll split that one off into a separate PR.

**Comment by 01micko** [comment]
I'd like this merged soon(ish) so that I can continue with #13 

I already have NLS working locally, just need to tidy up over the week end. 

OTOH, I can incorporate this with the NLS PR if that's easier, not much extra work for me really.

**Comment by johanmalm** [comment]
Sorry about delay... the TODO list just grew :smile:

**Comment by 01micko** [comment]
All good, I know your busy :smile:

**Pull request merged**
